version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: elephant-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "0.0.0.0:3306:3306"
    volumes:
      - hiding-data:/var/lib/mysql

volumes:
  hiding-data:
